### ISSUE TITLE
Could this menu have submenu?

### ISSUE THREAD

**Issue by BotellaA** [vparadis/vue-radial-menu#2]
I am looking for submenus, like a second ring of buttons. Could it be possible to do it with nested `vue-radial-menu`?

**Comment by vparadis** [comment]
This is untested as I do not have the means to test right now, but it should be possible, yes.

You can assume manual control of the state (open or closed) for the menu by passing an `open` prop. Doing this will prevent the menu from closing when you select an option.

Since menu items can contain nodes of any type, so long as it is a valid child, you should be able to put nested menus as child and close the main menu only if a child's option is selected.

I am unsure about the behavior of the animations however.
